version: '3'
services:
  web:
    container_name: ryuichi_nginx_dev
    platform: linux/amd64
    image: nginx:1.21
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
  app:
    platform: linux/amd64
    container_name: ryuichi_api_dev
    build: ./docker/php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    container_name: ryuichi_db_dev
    platform: linux/amd64
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    container_name: ryuichi_db_admin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    depends_on:
      - db

volumes:
  db-volume:
  maildir: {}
